name: Run unittests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup-dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: dotnet-tests-report
        uses: zyborg/dotnet-tests-report@v1.4.4
        with:
          project_path: UnitTests
          report_name: unittest_report
          report_title: UnitTest Report
          github_token: ${{ secrets.GITHUB_TOKEN }}